apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: green-ingress
  namespace: submodule-template  
spec:
  rules:
  - host: green.com
    http:
      paths:
      - path: /
        backend:
          serviceName: green-service
          servicePort: 80